/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.p1.frontend;

import com.mycompany.p1.backend.Enfermeiro;
import com.mycompany.p1.backend.MenuBack;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marin
 */
public class ListarEnfermeiros extends javax.swing.JFrame {

    /**
     * Creates new form ListarEnfermeiros
     */
    private ArrayList<Enfermeiro> listaEnfermeiros;
    private MenuBack menuB;
    
    public ListarEnfermeiros(MenuBack menu, ArrayList<Enfermeiro> lista) {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.listaEnfermeiros = lista;
        this.menuB = menu;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int linha = 0; // Inicializa a linha
     
        for (Enfermeiro enfermeiro : listaEnfermeiros) {
     
        model.addRow(new Object[]{ // Adiciona uma nova linha na tabela
            enfermeiro.getNomePessoal(),
            enfermeiro.getDataNascimento(),
            enfermeiro.getEndereco().getRua(),
            enfermeiro.getContato().getTelefone(),
            enfermeiro.getGenero().M,
            enfermeiro.getSetor(),
            enfermeiro.getChSemanal(),
            enfermeiro.isTreinadoOpRX(),
            "Edit", 
            "Delete" 
            
        });
        linha++; 
    }
        jTable1.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseClicked(MouseEvent e) {
            int column = jTable1.getColumnModel().getColumnIndexAtX(e.getX());
            int row = e.getY() / jTable1.getRowHeight();

        if (row < jTable1.getRowCount() && row >= 0 && column < jTable1.getColumnCount() && column >= 0) {
            if (row < jTable1.getRowCount() && row >= 0 && column < jTable1.getColumnCount() && column >= 0) {
                Object idValue = jTable1.getValueAt(row, 0);
                int id = Integer.parseInt(String.valueOf(idValue));
                System.out.println("ID do paciente na linha " + row + ": " + id);
                Object value = jTable1.getValueAt(row, column);
            if (value instanceof String && ((String) value).equals("Edit")) {
                new EditEnfermeiro(menuB, row).setVisible(true);
                setVisible(false);
                
                System.out.println("Editar paciente na linha: " + row);
            } else if (value instanceof String && ((String) value).equals("Delete")) {
                menuB.excluirEnfermeiro(row);
                setVisible(false);
                System.out.println("Excluir paciente na linha: " + row);
            }
        }
    }
}});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOME", "DATA DE NASCIMENTO", "ENDEREÇO", "CONTATO",
                "GENERO", "SETOR", "CHSEMANAL", "TREINADO_OPRX", "EDIT",
                "DELETE"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 851, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarEnfermeiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarEnfermeiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarEnfermeiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarEnfermeiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        ArrayList<Enfermeiro> lista = new ArrayList();
        MenuBack menu = new MenuBack();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarEnfermeiros(menu,lista).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
